const LOGIN = 'LOGIN';
const GET_CURRENCYS = 'GET_CURRENCYS';
const ADD_EXPENSES = 'ADD_EXPENSES';
const DELETE_EXPENSE = 'DELETE_EXPENSE';
const EDIT_EXPENSE = 'EDIT_EXPENSE';
const ID_TO_EDIT = 'ID_TO_EDIT';
const EDIT_FORM = 'EDIT_FORM';

export { LOGIN,
  GET_CURRENCYS,
  ADD_EXPENSES, DELETE_EXPENSE, EDIT_EXPENSE, ID_TO_EDIT, EDIT_FORM };
