const LOGIN = 'LOGIN';
const GET_CURRENCYS = 'GET_CURRENCYS';
const ADD_EXPENSES = 'GET_EXPENSES';
const DELETE_EXPENSE = 'DELETE_EXPENSE';

export { LOGIN, GET_CURRENCYS, ADD_EXPENSES, DELETE_EXPENSE };
